// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKraFhtaHpYCzyKxZwqQ8Ob6uPvmHPq84',
    appId: '1:218818413611:web:091e743df3b67e1357d66e',
    messagingSenderId: '218818413611',
    projectId: 'final-project-10eae',
    authDomain: 'final-project-10eae.firebaseapp.com',
    databaseURL: 'https://final-project-10eae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-10eae.appspot.com',
    measurementId: 'G-K2N5D0GZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4dy489pUFkOYWmM1pNwAXFKrW7b0dSqA',
    appId: '1:218818413611:android:e4e9e0f718b6ed0a57d66e',
    messagingSenderId: '218818413611',
    projectId: 'final-project-10eae',
    databaseURL: 'https://final-project-10eae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-10eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlQaFlDSR_ob0m4UCEXzKywdJkD4TQd74',
    appId: '1:218818413611:ios:a48b4bf00d513b9c57d66e',
    messagingSenderId: '218818413611',
    projectId: 'final-project-10eae',
    databaseURL: 'https://final-project-10eae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-10eae.appspot.com',
    iosClientId: '218818413611-3fdqcuj46ggbacc738uoo4t208uosj5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlQaFlDSR_ob0m4UCEXzKywdJkD4TQd74',
    appId: '1:218818413611:ios:a48b4bf00d513b9c57d66e',
    messagingSenderId: '218818413611',
    projectId: 'final-project-10eae',
    databaseURL: 'https://final-project-10eae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-10eae.appspot.com',
    iosClientId: '218818413611-3fdqcuj46ggbacc738uoo4t208uosj5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKraFhtaHpYCzyKxZwqQ8Ob6uPvmHPq84',
    appId: '1:218818413611:web:34fa146b204b7ce757d66e',
    messagingSenderId: '218818413611',
    projectId: 'final-project-10eae',
    authDomain: 'final-project-10eae.firebaseapp.com',
    databaseURL: 'https://final-project-10eae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-10eae.appspot.com',
    measurementId: 'G-EB06M3XTD2',
  );
}
